// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book_purchases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBookPurchase = `-- name: CreateBookPurchase :one
INSERT INTO book_purchases (user_id, book_id, gateway, reference, amount, currency, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, user_id, book_id, gateway, reference, amount, currency, status, created_at, updated_at
`

type CreateBookPurchaseParams struct {
	UserID    uuid.UUID `json:"user_id"`
	BookID    uuid.UUID `json:"book_id"`
	Gateway   string    `json:"gateway"`
	Reference string    `json:"reference"`
	Amount    int64     `json:"amount"`
	Currency  string    `json:"currency"`
}

func (q *Queries) CreateBookPurchase(ctx context.Context, arg CreateBookPurchaseParams) (BookPurchase, error) {
	row := q.db.QueryRow(ctx, createBookPurchase,
		arg.UserID,
		arg.BookID,
		arg.Gateway,
		arg.Reference,
		arg.Amount,
		arg.Currency,
	)
	var i BookPurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Gateway,
		&i.Reference,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookPurchaseByReference = `-- name: GetBookPurchaseByReference :one
SELECT id, user_id, book_id, gateway, reference, amount, currency, status, created_at, updated_at FROM book_purchases WHERE reference = $1
`

func (q *Queries) GetBookPurchaseByReference(ctx context.Context, reference string) (BookPurchase, error) {
	row := q.db.QueryRow(ctx, getBookPurchaseByReference, reference)
	var i BookPurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Gateway,
		&i.Reference,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookPurchases = `-- name: ListBookPurchases :many
SELECT id, user_id, book_id, gateway, reference, amount, currency, status, created_at, updated_at FROM book_purchases
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBookPurchasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin: paginated purchase log across all three gateways.
func (q *Queries) ListBookPurchases(ctx context.Context, arg ListBookPurchasesParams) ([]BookPurchase, error) {
	rows, err := q.db.Query(ctx, listBookPurchases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookPurchase{}
	for rows.Next() {
		var i BookPurchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Gateway,
			&i.Reference,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPurchasedBooks = `-- name: ListMyPurchasedBooks :many
SELECT b.id, b.title, b.author, b.description, b.cover_image_url, b.file_url, b.price_kobo, b.price_usd_cents, b.is_published, b.created_at, b.updated_at FROM books b
JOIN book_purchases bp ON bp.book_id = b.id
WHERE bp.user_id = $1 AND bp.status = 'success'
ORDER BY bp.created_at DESC
`

// What a signed-in buyer sees in "My books" — only successful purchases,
// joined with the book itself so the frontend gets title/cover/file in
// one call.
func (q *Queries) ListMyPurchasedBooks(ctx context.Context, userID uuid.UUID) ([]Book, error) {
	rows, err := q.db.Query(ctx, listMyPurchasedBooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CoverImageUrl,
			&i.FileUrl,
			&i.PriceKobo,
			&i.PriceUsdCents,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookPurchaseStatus = `-- name: MarkBookPurchaseStatus :one
UPDATE book_purchases SET status = $2, updated_at = now()
WHERE reference = $1
RETURNING id, user_id, book_id, gateway, reference, amount, currency, status, created_at, updated_at
`

type MarkBookPurchaseStatusParams struct {
	Reference string `json:"reference"`
	Status    string `json:"status"`
}

func (q *Queries) MarkBookPurchaseStatus(ctx context.Context, arg MarkBookPurchaseStatusParams) (BookPurchase, error) {
	row := q.db.QueryRow(ctx, markBookPurchaseStatus, arg.Reference, arg.Status)
	var i BookPurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Gateway,
		&i.Reference,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
