// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published, created_at, updated_at
`

type CreateBookParams struct {
	Title         string `json:"title"`
	Author        string `json:"author"`
	Description   string `json:"description"`
	CoverImageUrl string `json:"cover_image_url"`
	FileUrl       string `json:"file_url"`
	PriceKobo     int64  `json:"price_kobo"`
	PriceUsdCents int64  `json:"price_usd_cents"`
	IsPublished   bool   `json:"is_published"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.CoverImageUrl,
		arg.FileUrl,
		arg.PriceKobo,
		arg.PriceUsdCents,
		arg.IsPublished,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CoverImageUrl,
		&i.FileUrl,
		&i.PriceKobo,
		&i.PriceUsdCents,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published, created_at, updated_at FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CoverImageUrl,
		&i.FileUrl,
		&i.PriceKobo,
		&i.PriceUsdCents,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBooks = `-- name: ListAllBooks :many
SELECT id, title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published, created_at, updated_at FROM books
ORDER BY created_at DESC
`

// Admin: includes unpublished/draft books.
func (q *Queries) ListAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CoverImageUrl,
			&i.FileUrl,
			&i.PriceKobo,
			&i.PriceUsdCents,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBooks = `-- name: ListPublishedBooks :many
SELECT id, title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published, created_at, updated_at FROM books
WHERE is_published = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListPublishedBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listPublishedBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CoverImageUrl,
			&i.FileUrl,
			&i.PriceKobo,
			&i.PriceUsdCents,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2, author = $3, description = $4, cover_image_url = $5, file_url = $6,
    price_kobo = $7, price_usd_cents = $8, is_published = $9, updated_at = now()
WHERE id = $1
RETURNING id, title, author, description, cover_image_url, file_url, price_kobo, price_usd_cents, is_published, created_at, updated_at
`

type UpdateBookParams struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Author        string    `json:"author"`
	Description   string    `json:"description"`
	CoverImageUrl string    `json:"cover_image_url"`
	FileUrl       string    `json:"file_url"`
	PriceKobo     int64     `json:"price_kobo"`
	PriceUsdCents int64     `json:"price_usd_cents"`
	IsPublished   bool      `json:"is_published"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.CoverImageUrl,
		arg.FileUrl,
		arg.PriceKobo,
		arg.PriceUsdCents,
		arg.IsPublished,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CoverImageUrl,
		&i.FileUrl,
		&i.PriceKobo,
		&i.PriceUsdCents,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
