// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO course_chapters (course_id, title, position)
VALUES ($1, $2, $3)
RETURNING id, course_id, title, position, created_at
`

type CreateChapterParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Title    string    `json:"title"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (CourseChapter, error) {
	row := q.db.QueryRow(ctx, createChapter, arg.CourseID, arg.Title, arg.Position)
	var i CourseChapter
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (title, slug, summary, price_kobo, is_published, thumbnail_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url
`

type CreateCourseParams struct {
	Title        string `json:"title"`
	Slug         string `json:"slug"`
	Summary      string `json:"summary"`
	PriceKobo    int64  `json:"price_kobo"`
	IsPublished  bool   `json:"is_published"`
	ThumbnailUrl string `json:"thumbnail_url"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.PriceKobo,
		arg.IsPublished,
		arg.ThumbnailUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.PriceKobo,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM course_chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url FROM courses WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.PriceKobo,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.PriceKobo,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}

const listAllCourses = `-- name: ListAllCourses :many
SELECT id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url FROM courses
ORDER BY created_at DESC
`

// Admin: includes unpublished/draft courses.
func (q *Queries) ListAllCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.PriceKobo,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByCourse = `-- name: ListChaptersByCourse :many
SELECT id, course_id, title, position, created_at FROM course_chapters
WHERE course_id = $1
ORDER BY position ASC
`

func (q *Queries) ListChaptersByCourse(ctx context.Context, courseID uuid.UUID) ([]CourseChapter, error) {
	rows, err := q.db.Query(ctx, listChaptersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseChapter{}
	for rows.Next() {
		var i CourseChapter
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url FROM courses
WHERE is_published = TRUE
ORDER BY created_at DESC
`

// Public: what the homepage course carousel fetches.
func (q *Queries) ListPublishedCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.PriceKobo,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $2, summary = $3, price_kobo = $4, is_published = $5, thumbnail_url = $6, updated_at = now()
WHERE id = $1
RETURNING id, title, slug, summary, price_kobo, is_published, created_at, updated_at, thumbnail_url
`

type UpdateCourseParams struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Summary      string    `json:"summary"`
	PriceKobo    int64     `json:"price_kobo"`
	IsPublished  bool      `json:"is_published"`
	ThumbnailUrl string    `json:"thumbnail_url"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.PriceKobo,
		arg.IsPublished,
		arg.ThumbnailUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.PriceKobo,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}
