// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const enrollUserInCourse = `-- name: EnrollUserInCourse :one
INSERT INTO enrollments (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT (user_id, course_id) DO NOTHING
RETURNING id, user_id, course_id, enrolled_at
`

type EnrollUserInCourseParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) EnrollUserInCourse(ctx context.Context, arg EnrollUserInCourseParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, enrollUserInCourse, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
	)
	return i, err
}

const isUserEnrolled = `-- name: IsUserEnrolled :one
SELECT EXISTS (
    SELECT 1 FROM enrollments WHERE user_id = $1 AND course_id = $2
) AS enrolled
`

type IsUserEnrolledParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) IsUserEnrolled(ctx context.Context, arg IsUserEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEnrolled, arg.UserID, arg.CourseID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const listUserEnrollments = `-- name: ListUserEnrollments :many
SELECT course_id FROM enrollments WHERE user_id = $1
`

// Used to gate access: which course IDs this signed-in user can open.
func (q *Queries) ListUserEnrollments(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserEnrollments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
