// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Author        string             `json:"author"`
	Description   string             `json:"description"`
	CoverImageUrl string             `json:"cover_image_url"`
	FileUrl       string             `json:"file_url"`
	PriceKobo     int64              `json:"price_kobo"`
	PriceUsdCents int64              `json:"price_usd_cents"`
	IsPublished   bool               `json:"is_published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BookPurchase struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	BookID    uuid.UUID          `json:"book_id"`
	Gateway   string             `json:"gateway"`
	Reference string             `json:"reference"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Course struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Summary      string             `json:"summary"`
	PriceKobo    int64              `json:"price_kobo"`
	IsPublished  bool               `json:"is_published"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ThumbnailUrl string             `json:"thumbnail_url"`
}

type CourseChapter struct {
	ID        uuid.UUID          `json:"id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Title     string             `json:"title"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CourseID   uuid.UUID          `json:"course_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CourseID          uuid.NullUUID      `json:"course_id"`
	PaystackReference string             `json:"paystack_reference"`
	AmountKobo        int64              `json:"amount_kobo"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SiteSetting struct {
	ID                bool               `json:"id"`
	PastorName        string             `json:"pastor_name"`
	PastorBio         string             `json:"pastor_bio"`
	PastorPhotoUrl    string             `json:"pastor_photo_url"`
	CampusesCount     string             `json:"campuses_count"`
	YearsLeadership   string             `json:"years_leadership"`
	ContinentsReached string             `json:"continents_reached"`
	BooksUrl          string             `json:"books_url"`
	WebsiteUrl        string             `json:"website_url"`
	ContactEmail      string             `json:"contact_email"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	HeroVideoUrl      string             `json:"hero_video_url"`
	Philosophy1Title  string             `json:"philosophy_1_title"`
	Philosophy1Body   string             `json:"philosophy_1_body"`
	Philosophy2Title  string             `json:"philosophy_2_title"`
	Philosophy2Body   string             `json:"philosophy_2_body"`
	Philosophy3Title  string             `json:"philosophy_3_title"`
	Philosophy3Body   string             `json:"philosophy_3_body"`
}

type Subscriber struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	BrevoSynced bool               `json:"brevo_synced"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
