// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, course_id, paystack_reference, amount_kobo, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, course_id, paystack_reference, amount_kobo, status, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID            uuid.UUID     `json:"user_id"`
	CourseID          uuid.NullUUID `json:"course_id"`
	PaystackReference string        `json:"paystack_reference"`
	AmountKobo        int64         `json:"amount_kobo"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.CourseID,
		arg.PaystackReference,
		arg.AmountKobo,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.PaystackReference,
		&i.AmountKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, user_id, course_id, paystack_reference, amount_kobo, status, created_at, updated_at FROM payments WHERE paystack_reference = $1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, paystackReference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, paystackReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.PaystackReference,
		&i.AmountKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, user_id, course_id, paystack_reference, amount_kobo, status, created_at, updated_at FROM payments
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin: paginated payment log.
func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.PaystackReference,
			&i.AmountKobo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentStatus = `-- name: MarkPaymentStatus :one
UPDATE payments SET status = $2, updated_at = now()
WHERE paystack_reference = $1
RETURNING id, user_id, course_id, paystack_reference, amount_kobo, status, created_at, updated_at
`

type MarkPaymentStatusParams struct {
	PaystackReference string `json:"paystack_reference"`
	Status            string `json:"status"`
}

func (q *Queries) MarkPaymentStatus(ctx context.Context, arg MarkPaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentStatus, arg.PaystackReference, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.PaystackReference,
		&i.AmountKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumSuccessfulPaymentsKobo = `-- name: SumSuccessfulPaymentsKobo :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS total_kobo
FROM payments
WHERE status = 'success'
`

// Admin dashboard: total revenue.
func (q *Queries) SumSuccessfulPaymentsKobo(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumSuccessfulPaymentsKobo)
	var total_kobo int64
	err := row.Scan(&total_kobo)
	return total_kobo, err
}
