// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountSubscribers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookPurchase(ctx context.Context, arg CreateBookPurchaseParams) (BookPurchase, error)
	CreateChapter(ctx context.Context, arg CreateChapterParams) (CourseChapter, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSubscriber(ctx context.Context, email string) (Subscriber, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id uuid.UUID) error
	DeleteChapter(ctx context.Context, id uuid.UUID) error
	DeleteCourse(ctx context.Context, id uuid.UUID) error
	EnrollUserInCourse(ctx context.Context, arg EnrollUserInCourseParams) (Enrollment, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (Book, error)
	GetBookPurchaseByReference(ctx context.Context, reference string) (BookPurchase, error)
	GetCourseByID(ctx context.Context, id uuid.UUID) (Course, error)
	GetCourseBySlug(ctx context.Context, slug string) (Course, error)
	GetPaymentByReference(ctx context.Context, paystackReference string) (Payment, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	IsUserEnrolled(ctx context.Context, arg IsUserEnrolledParams) (bool, error)
	// Admin: includes unpublished/draft books.
	ListAllBooks(ctx context.Context) ([]Book, error)
	// Admin: includes unpublished/draft courses.
	ListAllCourses(ctx context.Context) ([]Course, error)
	// Admin: paginated purchase log across all three gateways.
	ListBookPurchases(ctx context.Context, arg ListBookPurchasesParams) ([]BookPurchase, error)
	ListChaptersByCourse(ctx context.Context, courseID uuid.UUID) ([]CourseChapter, error)
	ListMyPurchasedBooks(ctx context.Context, userID uuid.UUID) ([]Book, error)
	// Admin: paginated payment log.
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListPublishedBooks(ctx context.Context) ([]Book, error)
	// Public: what the homepage course carousel fetches.
	ListPublishedCourses(ctx context.Context) ([]Course, error)
	// Admin: paginated subscriber list, e.g. for export.
	ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]Subscriber, error)
	// Used to gate access: which course IDs this signed-in user can open.
	ListUserEnrollments(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	// Admin: paginated user list.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkBookPurchaseStatus(ctx context.Context, arg MarkBookPurchaseStatusParams) (BookPurchase, error)
	MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) error
	MarkPaymentStatus(ctx context.Context, arg MarkPaymentStatusParams) (Payment, error)
	MarkSubscriberSynced(ctx context.Context, email string) error
	MarkUserVerified(ctx context.Context, id uuid.UUID) error
	// Used on password change / logout-everywhere.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	// Admin dashboard: total revenue.
	SumSuccessfulPaymentsKobo(ctx context.Context) (int64, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) (SiteSetting, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
