// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, pastor_name, pastor_bio, pastor_photo_url, campuses_count, years_leadership, continents_reached, books_url, website_url, contact_email, updated_at, hero_video_url FROM site_settings WHERE id = TRUE
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.PastorName,
		&i.PastorBio,
		&i.PastorPhotoUrl,
		&i.CampusesCount,
		&i.YearsLeadership,
		&i.ContinentsReached,
		&i.BooksUrl,
		&i.WebsiteUrl,
		&i.ContactEmail,
		&i.UpdatedAt,
		&i.HeroVideoUrl,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :one
UPDATE site_settings SET
    pastor_name = $1,
    pastor_bio = $2,
    pastor_photo_url = $3,
    campuses_count = $4,
    years_leadership = $5,
    continents_reached = $6,
    books_url = $7,
    website_url = $8,
    contact_email = $9,
    hero_video_url = $10,
    updated_at = now()
WHERE id = TRUE
RETURNING id, pastor_name, pastor_bio, pastor_photo_url, campuses_count, years_leadership, continents_reached, books_url, website_url, contact_email, updated_at, hero_video_url
`

type UpdateSiteSettingsParams struct {
	PastorName        string `json:"pastor_name"`
	PastorBio         string `json:"pastor_bio"`
	PastorPhotoUrl    string `json:"pastor_photo_url"`
	CampusesCount     string `json:"campuses_count"`
	YearsLeadership   string `json:"years_leadership"`
	ContinentsReached string `json:"continents_reached"`
	BooksUrl          string `json:"books_url"`
	WebsiteUrl        string `json:"website_url"`
	ContactEmail      string `json:"contact_email"`
	HeroVideoUrl      string `json:"hero_video_url"`
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, updateSiteSettings,
		arg.PastorName,
		arg.PastorBio,
		arg.PastorPhotoUrl,
		arg.CampusesCount,
		arg.YearsLeadership,
		arg.ContinentsReached,
		arg.BooksUrl,
		arg.WebsiteUrl,
		arg.ContactEmail,
		arg.HeroVideoUrl,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.PastorName,
		&i.PastorBio,
		&i.PastorPhotoUrl,
		&i.CampusesCount,
		&i.YearsLeadership,
		&i.ContinentsReached,
		&i.BooksUrl,
		&i.WebsiteUrl,
		&i.ContactEmail,
		&i.UpdatedAt,
		&i.HeroVideoUrl,
	)
	return i, err
}
