// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package sqlc

import (
	"context"
)

const countSubscribers = `-- name: CountSubscribers :one
SELECT count(*) FROM subscribers
`

func (q *Queries) CountSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (email)
VALUES ($1)
ON CONFLICT (lower(email)) DO NOTHING
RETURNING id, email, brevo_synced, created_at
`

func (q *Queries) CreateSubscriber(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.BrevoSynced,
		&i.CreatedAt,
	)
	return i, err
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, email, brevo_synced, created_at FROM subscribers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscribersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin: paginated subscriber list, e.g. for export.
func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.BrevoSynced,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriberSynced = `-- name: MarkSubscriberSynced :exec
UPDATE subscribers SET brevo_synced = TRUE WHERE email = $1
`

func (q *Queries) MarkSubscriberSynced(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markSubscriberSynced, email)
	return err
}
